/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import model.DataRecord;
import window.*;

import static org.junit.Assert.*;

import java.util.Random;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class MainWindowTest {
    Random random = new Random(8);

    @Test public void testMainWindow() {
        // テスト対象
        MainWindow mainWindow = new MainWindow();

        // テストデータ
        DataRecord record = new DataRecord();
        record.ItemName = "TestItem";
        record.Protein = this.random.nextDouble();
        record.Carbohydrate = this.random.nextDouble();
        record.Lipid = this.random.nextDouble();
        record.Calorie = this.random.nextDouble();
        mainWindow.SetRecord(record);

        // テスト結果
        JTable table = mainWindow.getTable();
        // 行数
        // assertEquals("行数が誤ってます", table.getRowCount(), 2);

    }
}
